window.scheduleData = {
  upper: {
    Понеділок: [
      {
        time: "10.00-10.50",
        subject: "Урок з Вікою Даніною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "-",
        linkText: "",
      },
      {
        time: "11.00-11.50",
        subject: "Урок з Марічкою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "-",
        linkText: "",
      },
      {
        time: "12.00-12.50",
        subject: "Урок з Ксюшою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "-",
        linkText: "",
      },
      {
        time: "15.00-15.50",
        subject: "Урок з Вікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "16.00-16.50",
        subject: "Урок з Ілля",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/79950004155?pwd=FgHHeKdpJHgWqbDB7tZmDpaV3kgVab.1",
        linkText: "Zoom",
      },
      {
        time: "18.00-18.50",
        subject: "Урок з Златою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/72715914681?pwd=QweeSKv99Tv5ebFwwAeDLO3xUBB9up.1",
        linkText: "Zoom",
      },
    ],
    Вівторок: [
      {
        time: "18.00-18.50",
        subject: "Урок з Іванною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/74561284373?pwd=btqSbLB8LRR9qsgvswiFSS7pXicWnp.1",
        linkText: "Zoom",
      },
      {
        time: "19.00-19.50",
        subject: "Урок з Поліною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/78261077907?pwd=1EyaRpoLRXmLB9TY14c03Ipec0JqoS.1",
        linkText: "Zoom",
      },
    ],
    Середа: [
      {
        time: "10.00-10.50",
        subject: "Урок з Вікою Даніною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "-",
        linkText: "",
      },
      {
        time: "11.00-11.50",
        subject: "Урок з Марічкою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "-",
        linkText: "",
      },
      {
        time: "12.00-12.50",
        subject: "Урок з Ксюшою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "-",
        linkText: "",
      },
      {
        time: "15.00-15.50",
        subject: "Урок з Вікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "20.10-21.00",
        subject: "Урок з Алісою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
    ],
    Четвер: [
      {
        time: "16.00-16.50",
        subject: "Урок з Євою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
    ],
    "П'ятниця": [
      {
        time: "17.00-17.50",
        subject: "Урок з Іванною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/74561284373?pwd=btqSbLB8LRR9qsgvswiFSS7pXicWnp.1",
        linkText: "Zoom",
      },
      {
        time: "18.00-19.20",
        subject: "Урок з Поліною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/78261077907?pwd=1EyaRpoLRXmLB9TY14c03Ipec0JqoS.1",
        linkText: "Zoom",
      },
      {
        time: "19.30-20.20",
        subject: "Урок з Алісою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
    ],
    Субота: [
      {
        time: "10.00-10.50",
        subject: "Урок з Златою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/72715914681?pwd=QweeSKv99Tv5ebFwwAeDLO3xUBB9up.1",
        linkText: "Zoom",
      },
    ],
    Неділя: [
      {
        time: "10.00-10.50",
        subject: "Урок з Ілля",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/79950004155?pwd=FgHHeKdpJHgWqbDB7tZmDpaV3kgVab.1",
        linkText: "Zoom",
      },
      {
        time: "12.00-12.50",
        subject: "Урок з Євою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
    ],
  },
  lower: {
    Понеділок: [
      {
        time: "10.00-10.50",
        subject: "Урок з Вікою Даніною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "-",
        linkText: "",
      },
      {
        time: "11.00-11.50",
        subject: "Урок з Марічкою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "-",
        linkText: "",
      },
      {
        time: "12.00-12.50",
        subject: "Урок з Ксюшою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "-",
        linkText: "",
      },
      {
        time: "15.00-15.50",
        subject: "Урок з Вікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "16.00-16.50",
        subject: "Урок з Ілля",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/79950004155?pwd=FgHHeKdpJHgWqbDB7tZmDpaV3kgVab.1",
        linkText: "Zoom",
      },
      {
        time: "18.00-18.50",
        subject: "Урок з Златою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/72715914681?pwd=QweeSKv99Tv5ebFwwAeDLO3xUBB9up.1",
        linkText: "Zoom",
      },
    ],
    Вівторок: [
      {
        time: "18.00-18.50",
        subject: "Урок з Іванною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/74561284373?pwd=btqSbLB8LRR9qsgvswiFSS7pXicWnp.1",
        linkText: "Zoom",
      },
      {
        time: "19.00-19.50",
        subject: "Урок з Поліною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/78261077907?pwd=1EyaRpoLRXmLB9TY14c03Ipec0JqoS.1",
        linkText: "Zoom",
      },
    ],
    Середа: [
      {
        time: "10.00-10.50",
        subject: "Урок з Вікою Даніною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "-",
        linkText: "",
      },
      {
        time: "11.00-11.50",
        subject: "Урок з Марічкою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "-",
        linkText: "",
      },
      {
        time: "12.00-12.50",
        subject: "Урок з Ксюшою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "-",
        linkText: "",
      },
      {
        time: "15.00-15.50",
        subject: "Урок з Вікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "20.10-21.00",
        subject: "Урок з Алісою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
    ],
    Четвер: [
      {
        time: "16.00-16.50",
        subject: "Урок з Євою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
    ],
    "П'ятниця": [
      {
        time: "17.00-17.50",
        subject: "Урок з Іванною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/74561284373?pwd=btqSbLB8LRR9qsgvswiFSS7pXicWnp.1",
        linkText: "Zoom",
      },
      {
        time: "18.00-19.20",
        subject: "Урок з Поліною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/78261077907?pwd=1EyaRpoLRXmLB9TY14c03Ipec0JqoS.1",
        linkText: "Zoom",
      },
      {
        time: "19.30-20.20",
        subject: "Урок з Алісою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
    ],
    Субота: [
      {
        time: "10.00-10.50",
        subject: "Урок з Златою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/72715914681?pwd=QweeSKv99Tv5ebFwwAeDLO3xUBB9up.1",
        linkText: "Zoom",
      },
    ],
    Неділя: [
      {
        time: "10.00-10.50",
        subject: "Урок з Ілля",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/79950004155?pwd=FgHHeKdpJHgWqbDB7tZmDpaV3kgVab.1",
        linkText: "Zoom",
      },
      {
        time: "12.00-12.50",
        subject: "Урок з Євою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
    ],
  },
};
