window.scheduleData = {
  upper: {
    Понеділок: [
      {
        time: "10.00-10.50",
        subject: "Урок з Вікою Даніною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/75195106340?pwd=4wfzWB28igMBPQTVdaeTYq2GyCvXdf.1",
        linkText: "",
      },
      {
        time: "11.00-11.50",
        subject: "Урок з Марічкою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/73365668510?pwd=Q68tpiIX7u3QtjFkyfLPGxIbXVacnX.1",
        linkText: "",
      },
      {
        time: "12.00-12.50",
        subject: "Урок з Ксюшою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/73754990250?pwd=MIeDxzctcaiPf9YNVQBFRwTnTybj2A.1",
        linkText: "",
      },
      {
        time: "15.00-15.50",
        subject: "Урок з Вікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "16.00-16.50",
        subject: "Урок з Іллею",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/79950004155?pwd=FgHHeKdpJHgWqbDB7tZmDpaV3kgVab.1",
        linkText: "Zoom",
      },
      {
        time: "18.00-18.50",
        subject: "Урок з Златою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/72715914681?pwd=QweeSKv99Tv5ebFwwAeDLO3xUBB9up.1",
        linkText: "Zoom",
      },
    ],
    Середа: [
      {
        time: "10.00-10.50",
        subject: "Урок з Вікою Даніною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/75195106340?pwd=4wfzWB28igMBPQTVdaeTYq2GyCvXdf.1",
        linkText: "",
      },
      {
        time: "11.00-11.50",
        subject: "Урок з Марічкою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/73365668510?pwd=Q68tpiIX7u3QtjFkyfLPGxIbXVacnX.1",
        linkText: "",
      },
      {
        time: "12.00-12.50",
        subject: "Урок з Ксюшою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/73754990250?pwd=MIeDxzctcaiPf9YNVQBFRwTnTybj2A.1",
        linkText: "",
      },
      {
        time: "15.00-15.50",
        subject: "Урок з Вікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
    ],
    Субота: [
      {
        time: "10.00-10.50",
        subject: "Урок з Златою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/72715914681?pwd=QweeSKv99Tv5ebFwwAeDLO3xUBB9up.1",
        linkText: "Zoom",
      },
    ],
    Неділя: [
      {
        time: "10.00-10.50",
        subject: "Урок з Іллею",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/79950004155?pwd=FgHHeKdpJHgWqbDB7tZmDpaV3kgVab.1",
        linkText: "Zoom",
      },
    ],
  },
  lower: {
    Понеділок: [
      {
        time: "10.00-10.50",
        subject: "Урок з Вікою Даніною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/75195106340?pwd=4wfzWB28igMBPQTVdaeTYq2GyCvXdf.1",
        linkText: "",
      },
      {
        time: "11.00-11.50",
        subject: "Урок з Марічкою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/73365668510?pwd=Q68tpiIX7u3QtjFkyfLPGxIbXVacnX.1",
        linkText: "",
      },
      {
        time: "12.00-12.50",
        subject: "Урок з Ксюшою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/73754990250?pwd=MIeDxzctcaiPf9YNVQBFRwTnTybj2A.1",
        linkText: "",
      },
      {
        time: "15.00-15.50",
        subject: "Урок з Вікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "16.00-16.50",
        subject: "Урок з Іллею",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/79950004155?pwd=FgHHeKdpJHgWqbDB7tZmDpaV3kgVab.1",
        linkText: "Zoom",
      },
      {
        time: "18.00-18.50",
        subject: "Урок з Златою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/72715914681?pwd=QweeSKv99Tv5ebFwwAeDLO3xUBB9up.1",
        linkText: "Zoom",
      },
    ],
    Середа: [
      {
        time: "10.00-10.50",
        subject: "Урок з Вікою Даніною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/75195106340?pwd=4wfzWB28igMBPQTVdaeTYq2GyCvXdf.1",
        linkText: "",
      },
      {
        time: "11.00-11.50",
        subject: "Урок з Марічкою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/73365668510?pwd=Q68tpiIX7u3QtjFkyfLPGxIbXVacnX.1",
        linkText: "",
      },
      {
        time: "12.00-12.50",
        subject: "Урок з Ксюшою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/73754990250?pwd=MIeDxzctcaiPf9YNVQBFRwTnTybj2A.1",
        linkText: "",
      },
      {
        time: "15.00-15.50",
        subject: "Урок з Вікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
    ],
    Субота: [
      {
        time: "10.00-10.50",
        subject: "Урок з Златою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/72715914681?pwd=QweeSKv99Tv5ebFwwAeDLO3xUBB9up.1",
        linkText: "Zoom",
      },
    ],
    Неділя: [
      {
        time: "10.00-10.50",
        subject: "Урок з Іллею",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/79950004155?pwd=FgHHeKdpJHgWqbDB7tZmDpaV3kgVab.1",
        linkText: "Zoom",
      },
    ],
  },
};
