window.scheduleData = {
  upper: {
    Понеділок: [
      {
        time: "10.35-12.10",
        subject: "Інструментальні середовища та технології",
        type: "pr",
        typeLabel: "Практика",
        teacher: "Тієвський І.О.",
        link: "https://classroom.google.com/c/ODQwOTkyNjAxNTM3",
        linkText: "Classroom",
      },
      {
        time: "12.20-13.55",
        subject: "Бази даних та бази знань",
        type: "pr",
        typeLabel: "Практика",
        teacher: "Тарануха В.Ю.",
        link: "https://us05web.zoom.us/j/7221055227?pwd=MTdmWG9oNDA0TXd0TGU2dFVSWXN0UT09",
        linkText: "Zoom",
      },
      {
        time: "22.00-23.30",
        subject: "English",
        type: "інд",
        typeLabel: "Реп",
        teacher: "Колош А.С.",
        link: "-",
        linkText: "кожен раз нове",
      },
    ],
    Вівторок: [
      {
        time: "8.40-10.15",
        subject: "Іноземна мова",
        type: "pr",
        typeLabel: "Практика",
        teacher: "Красовська І. В.",
        link: "https://us04web.zoom.us/j/79134168970?pwd=1ADoKZbh222p9CZDzTBGWnosp4KoyJ.1",
        linkText: "Zoom",
      },
      {
        time: "10.35-12.10",
        subject: "Алгоритми та структури даних",
        type: "pr",
        typeLabel: "Практика",
        teacher: "Закала П.А.",
        link: "https://meet.google.com/uxn-jbwq-nhn",
        linkText: "Meet",
      },
      {
        time: "16.00-16.50",
        subject: "Урок з Іванною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/74561284373?pwd=btqSbLB8LRR9qsgvswiFSS7pXicWnp.1",
        linkText: "Zoom",
      },
      {
        time: "17.00-17.50",
        subject: "Урок з Вікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "19.00-19.50",
        subject: "Урок з Ілльой",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/79950004155?pwd=FgHHeKdpJHgWqbDB7tZmDpaV3kgVab.1",
        linkText: "Zoom",
      },
      {
        time: "20.00-20.50",
        subject: "Урок з Алісой",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "21.00-21.50",
        subject: "Урок з Славой",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
    ],
    Середа: [
      {
        time: "8.40-10.15",
        subject: "Дослідження операцій",
        type: "pr",
        typeLabel: "Практика",
        teacher: "Кондратенко О.О.",
        link: "http://meet.google.com/stp-rrmy-uni",
        linkText: "Meet",
      },
      {
        time: "10.35-12.10",
        subject: "Теорія алгоритмів",
        type: "pr",
        typeLabel: "Практика",
        teacher: "Зубенко В.В.",
        link: "https://us05web.zoom.us/j/94539843232?pwd=OEhTRXBoUlNTNytUd3hzV2JuREhTZz09",
        linkText: "Zoom,",
      },
      {
        time: "12.20-13.55",
        subject: "Мова Python для візуалізації",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Карнаух Т. О.",
        link: "https://meet.google.com/ydt-adiv-yha",
        linkText: "Meet",
      },
      {
        time: "14.05-15.40",
        subject: "Бази даних та бази знань",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Завадський І. О.",
        link: "https://knu-ua.zoom.us/j/89311264406?pwd=GyiSgmIhoP5gNg6rDkyw6xqn2uiUb7.1",
        linkText: "Zoom",
      },
      {
        time: "16.00-16.50",
        subject: "Урок з Євою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "17.00-17.50",
        subject: "Урок з Нікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "18.00-19.20",
        subject: "Урок з Поліною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/78261077907?pwd=1EyaRpoLRXmLB9TY14c03Ipec0JqoS.1",
        linkText: "Zoom",
      },
      {
        time: "20.00-20.50",
        subject: "Урок з Марією",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "21.00-21.50",
        subject: "Урок з Ілльой",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/79950004155?pwd=FgHHeKdpJHgWqbDB7tZmDpaV3kgVab.1",
        linkText: "Zoom",
      },
    ],
    Четвер: [
      {
        time: "8.40-10.15",
        subject: "Інструментальні середовища та технології",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Омельчук Л. Л.",
        link: "https://meet.google.com/xro-rpnw-pff",
        linkText: "Meet",
      },
      {
        time: "10.35-12.10",
        subject: "Математична статистика",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Розора І. В.",
        link: "https://meet.google.com/fys-kfeu-unr",
        linkText: "Meet",
      },
      {
        time: "12.20-13.55",
        subject: "Бази даних та бази знань",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Завадський І. О.",
        link: "https://knu-ua.zoom.us/j/89311264406?pwd=GyiSgmIhoP5gNg6rDkyw6xqn2uiUb7.1",
        linkText: "Zoom",
      },
      {
        time: "16.00-16.50",
        subject: "Урок з Євою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "17.00-17.50",
        subject: "Урок з Вікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "18.00-18.50",
        subject: "Урок з Златою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/72715914681?pwd=QweeSKv99Tv5ebFwwAeDLO3xUBB9up.1",
        linkText: "Zoom",
      },
      {
        time: "19.00-19.50",
        subject: "Урок з Ілльой",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/79950004155?pwd=FgHHeKdpJHgWqbDB7tZmDpaV3kgVab.1",
        linkText: "Zoom",
      },
      {
        time: "20.00-20.50",
        subject: "Урок з Алісой",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "22.00-23.30",
        subject: "English",
        type: "інд",
        typeLabel: "Реп",
        teacher: "Колош А.С.",
        link: "-",
        linkText: "кожен раз нове",
      },
    ],
    "П'ятниця": [
      {
        time: "8.40-10.15",
        subject: "Дослідження операцій",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Заворотинський А. В.",
        link: "https://knu-ua.zoom.us/j/87660949816?pwd=1ac3aZPOVHGQTsTrAeCkXbL34jwrGC.1",
        linkText: "Zoom",
      },
      {
        time: "10.35-12.10",
        subject: "Теорія алгоритмів",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Шкільняк С. С.",
        link: "https://us04web.zoom.us/j/77713518929?pwd=K01sMDZxTXpQSEJPYk1ZeHFkOEVpdz09",
        linkText: "Zoom",
      },
      {
        time: "12.20-13.55",
        subject: "Дослідження операцій",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Заворотинський А. В.",
        link: "https://knu-ua.zoom.us/j/87660949816?pwd=1ac3aZPOVHGQTsTrAeCkXbL34jwrGC.1",
        linkText: "Zoom",
      },
      {
        time: "15.00-15.50",
        subject: "Урок з Златою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/72715914681?pwd=QweeSKv99Tv5ebFwwAeDLO3xUBB9up.1",
        linkText: "Zoom",
      },
      {
        time: "16.00-16.50",
        subject: "Урок з Нікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "17.00-17.50",
        subject: "Урок з Іванною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/74561284373?pwd=btqSbLB8LRR9qsgvswiFSS7pXicWnp.1",
        linkText: "Zoom",
      },
      {
        time: "18.00-19.20",
        subject: "Урок з Поліною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/78261077907?pwd=1EyaRpoLRXmLB9TY14c03Ipec0JqoS.1",
        linkText: "Zoom",
      },
    ],
  },
  lower: {
    Понеділок: [
      {
        time: "10.35-12.10",
        subject: "Інструментальні середовища та технології",
        type: "pr",
        typeLabel: "Практика",
        teacher: "Тієвський І.О.",
        link: "https://classroom.google.com/c/ODQwOTkyNjAxNTM3",
        linkText: "Classroom",
      },
      {
        time: "12.20-13.55",
        subject: "Бази даних та бази знань",
        type: "pr",
        typeLabel: "Практика",
        teacher: "Тарануха В.Ю.",
        link: "https://us05web.zoom.us/j/7221055227?pwd=MTdmWG9oNDA0TXd0TGU2dFVSWXN0UT09",
        linkText: "Zoom",
      },
      {
        time: "14.05-15.40",
        subject: "Мова Python для візуалізації",
        type: "pr",
        typeLabel: "Практика",
        teacher: "Ляшко А. В.",
        link: "https://classroom.google.com/c/ODQxMTY3MTE3MDM5",
        linkText: "classroom",
      },
      {
        time: "22.00-23.30",
        subject: "English",
        type: "інд",
        typeLabel: "Реп",
        teacher: "Колош А.С.",
        link: "-",
        linkText: "кожен раз нове",
      },
    ],
    Вівторок: [
      {
        time: "8.40-10.15",
        subject: "Іноземна мова",
        type: "pr",
        typeLabel: "Практика",
        teacher: "Красовська І. В.",
        link: "https://us04web.zoom.us/j/79134168970?pwd=1ADoKZbh222p9CZDzTBGWnosp4KoyJ.1",
        linkText: "Zoom",
      },
      {
        time: "10.35-12.10",
        subject: "Алгоритми та структури даних",
        type: "pr",
        typeLabel: "Практика",
        teacher: "Закала П.А.",
        link: "https://meet.google.com/uxn-jbwq-nhn",
        linkText: "Meet",
      },
      {
        time: "12.20-13.55",
        subject: "Математична статистика",
        type: "pr",
        typeLabel: "Практика",
        teacher: "Бездір О.О.",
        link: "https://meet.google.com/nry-pvjm-iqr",
        linkText: "Meet",
      },
      {
        time: "16.00-16.50",
        subject: "Урок з Іванною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/74561284373?pwd=btqSbLB8LRR9qsgvswiFSS7pXicWnp.1",
        linkText: "Zoom",
      },
      {
        time: "17.00-17.50",
        subject: "Урок з Вікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "19.00-19.50",
        subject: "Урок з Ілльой",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/79950004155?pwd=FgHHeKdpJHgWqbDB7tZmDpaV3kgVab.1",
        linkText: "Zoom",
      },
      {
        time: "20.00-20.50",
        subject: "Урок з Алісой",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "21.00-21.50",
        subject: "Урок з Славой",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
    ],
    Середа: [
      {
        time: "8.40-10.15",
        subject: "Дослідження операцій",
        type: "pr",
        typeLabel: "Практика",
        teacher: "Кондратенко О.О.",
        link: "http://meet.google.com/stp-rrmy-uni",
        linkText: "Meet",
      },
      {
        time: "10.35-12.10",
        subject: "Теорія алгоритмів",
        type: "pr",
        typeLabel: "Практика",
        teacher: "Зубенко В.В.",
        link: "https://us05web.zoom.us/j/94539843232?pwd=OEhTRXBoUlNTNytUd3hzV2JuREhTZz09",
        linkText: "Zoom,",
      },
      {
        time: "12.20-13.55",
        subject: "Алгоритми та структури даних",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Бобиль Б. В.",
        link: "https://us06web.zoom.us/j/3530588568?pwd=VDZpbWFRWHU1Y1N1NThSaURKaGM4QT09",
        linkText: "Zoom",
      },
      {
        time: "14.05-15.40",
        subject: "Бази даних та бази знань",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Завадський І. О.",
        link: "https://knu-ua.zoom.us/j/89311264406?pwd=GyiSgmIhoP5gNg6rDkyw6xqn2uiUb7.1",
        linkText: "Zoom",
      },
      {
        time: "16.00-16.50",
        subject: "Урок з Євою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "17.00-17.50",
        subject: "Урок з Нікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "18.00-19.20",
        subject: "Урок з Поліною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/78261077907?pwd=1EyaRpoLRXmLB9TY14c03Ipec0JqoS.1",
        linkText: "Zoom",
      },
      {
        time: "20.00-20.50",
        subject: "Урок з Марією",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "21.00-21.50",
        subject: "Урок з Ілльой",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/79950004155?pwd=FgHHeKdpJHgWqbDB7tZmDpaV3kgVab.1",
        linkText: "Zoom",
      },
      {
        time: "22.00-23.30",
        subject: "English",
        type: "інд",
        typeLabel: "Реп",
        teacher: "Колош А.С.",
        link: "-",
        linkText: "кожен раз нове",
      },
    ],
    Четвер: [
      {
        time: "8.40-10.15",
        subject: "Інструментальні середовища та технології",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Omelchuk L. L.",
        link: "https://meet.google.com/xro-rpnw-pff",
        linkText: "Meet",
      },
      {
        time: "10.35-12.10",
        subject: "Математична статистика",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Розора І. В.",
        link: "https://meet.google.com/fys-kfeu-unr",
        linkText: "Meet",
      },
      {
        time: "12.20-13.55",
        subject: "Бази даних та бази знань",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Завадський І. О.",
        link: "https://knu-ua.zoom.us/j/89311264406?pwd=GyiSgmIhoP5gNg6rDkyw6xqn2uiUb7.1",
        linkText: "Zoom",
      },
      {
        time: "16.00-16.50",
        subject: "Урок з Євою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "17.00-17.50",
        subject: "Урок з Вікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "18.00-18.50",
        subject: "Урок з Златою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/72715914681?pwd=QweeSKv99Tv5ebFwwAeDLO3xUBB9up.1",
        linkText: "Zoom",
      },
      {
        time: "19.00-19.50",
        subject: "Урок з Ілльой",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/79950004155?pwd=FgHHeKdpJHgWqbDB7tZmDpaV3kgVab.1",
        linkText: "Zoom",
      },
      {
        time: "20.00-20.50",
        subject: "Урок з Алісой",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
    ],
    "П'ятниця": [
      {
        time: "8.40-10.15",
        subject: "Дослідження операцій",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Заворотинський А. В.",
        link: "https://knu-ua.zoom.us/j/87660949816?pwd=1ac3aZPOVHGQTsTrAeCkXbL34jwrGC.1",
        linkText: "Zoom",
      },
      {
        time: "10.35-12.10",
        subject: "Теорія алгоритмів",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Шкільняк С. С.",
        link: "https://us04web.zoom.us/j/77713518929?pwd=K01sMDZxTXpQSEJPYk1ZeHFkOEVpdz09",
        linkText: "Zoom",
      },
      {
        time: "12.20-13.55",
        subject: "Дослідження операцій",
        type: "lek",
        typeLabel: "Лекція",
        teacher: "Заворотинський А. В.",
        link: "https://knu-ua.zoom.us/j/87660949816?pwd=1ac3aZPOVHGQTsTrAeCkXbL34jwrGC.1",
        linkText: "Zoom",
      },
      {
        time: "15.00-15.50",
        subject: "Урок з Златою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/72715914681?pwd=QweeSKv99Tv5ebFwwAeDLO3xUBB9up.1",
        linkText: "Zoom",
      },
      {
        time: "16.00-16.50",
        subject: "Урок з Нікою",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/9962482824?pwd=23Wry7aRgv7nbluhweOFcpKrREDwgw.1",
        linkText: "Zoom",
      },
      {
        time: "17.00-17.50",
        subject: "Урок з Іванною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/74561284373?pwd=btqSbLB8LRR9qsgvswiFSS7pXicWnp.1",
        linkText: "Zoom",
      },
      {
        time: "18.00-19.20",
        subject: "Урок з Поліною",
        type: "ind",
        typeLabel: "інд",
        teacher: "",
        link: "https://us04web.zoom.us/j/78261077907?pwd=1EyaRpoLRXmLB9TY14c03Ipec0JqoS.1",
        linkText: "Zoom",
      },
    ],
  },
};
